--wool into string
minetest.register_craft({
    output="farming:string 4",
    recipe={
        {"wool:white",},
    }
})
minetest.register_craft({
    output="coloredstrings:string_grey 4",
    recipe={
        {"wool:grey",},
    }
})
minetest.register_craft({
    output="coloredstrings:string_dark_grey 4",
    recipe={
        {"wool:dark_grey",},
    }
})
minetest.register_craft({
    output="coloredstrings:string_black 4",
    recipe={
        {"wool:black",},
    }
})
minetest.register_craft({
    output="coloredstrings:string_blue 4",
    recipe={
        {"wool:blue",},
    }
})
minetest.register_craft({
    output="coloredstrings:string_cyan 4",
    recipe={
        {"wool:cyan",},
    }
})
minetest.register_craft({
    output="coloredstrings:string_green 4",
    recipe={
        {"wool:green",},
    }
})
minetest.register_craft({
    output="coloredstrings:string_dark_green 4",
    recipe={
        {"wool:dark_green",},
    }
})
minetest.register_craft({
    output="coloredstrings:string_yellow 4",
    recipe={
        {"wool:yellow",},
    }
})
minetest.register_craft({
    output="coloredstrings:string_orange 4",
    recipe={
        {"wool:orange",},
    }
})
minetest.register_craft({
    output="coloredstrings:string_brown 4",
    recipe={
        {"wool:brown",},
    }
})
minetest.register_craft({
    output="coloredstrings:string_red 4",
    recipe={
        {"wool:red",},
    }
})
minetest.register_craft({
    output="coloredstrings:string_pink 4",
    recipe={
        {"wool:pink",},
    }
})
minetest.register_craft({
    output="coloredstrings:string_magenta 4",
    recipe={
        {"wool:magenta",},
    }
})
minetest.register_craft({
    output="coloredstrings:string_violet 4",
    recipe={
        {"wool:violet",},
    }
})
--string into wool
minetest.register_craft({
    output="wool:white",
    recipe={
        {"farming:string","farming:string",},
        {"farming:string","farming:string",},
    }
})
minetest.register_craft({
    output="wool:grey",
    recipe={
        {"coloredstrings:string_grey","coloredstrings:string_grey",},
        {"coloredstrings:string_grey","coloredstrings:string_grey",},
    }
})
minetest.register_craft({
    output="wool:dark_grey",
    recipe={
        {"coloredstrings:string_dark_grey","coloredstrings:string_dark_grey",},
        {"coloredstrings:string_dark_grey","coloredstrings:string_dark_grey",},
    }
})
minetest.register_craft({
    output="wool:black",
    recipe={
        {"coloredstrings:string_black","coloredstrings:string_black",},
        {"coloredstrings:string_black","coloredstrings:string_black",},
    }
})
minetest.register_craft({
    output="wool:blue",
    recipe={
        {"coloredstrings:string_blue","coloredstrings:string_blue",},
        {"coloredstrings:string_blue","coloredstrings:string_blue",},
    }
})
minetest.register_craft({
    output="wool:cyan",
    recipe={
        {"coloredstrings:string_cyan","coloredstrings:string_cyan",},
        {"coloredstrings:string_cyan","coloredstrings:string_cyan",},
    }
})
minetest.register_craft({
    output="wool:green",
    recipe={
        {"coloredstrings:string_green","coloredstrings:string_green",},
        {"coloredstrings:string_green","coloredstrings:string_green",},
    }
})
minetest.register_craft({
    output="wool:dark_green",
    recipe={
        {"coloredstrings:string_dark_green","coloredstrings:string_dark_green",},
        {"coloredstrings:string_dark_green","coloredstrings:string_dark_green",},
    }
})
minetest.register_craft({
    output="wool:yellow",
    recipe={
        {"coloredstrings:string_yellow","coloredstrings:string_yellow",},
        {"coloredstrings:string_yellow","coloredstrings:string_yellow",},
    }
})
minetest.register_craft({
    output="wool:orange",
    recipe={
        {"coloredstrings:string_orange","coloredstrings:string_orange",},
        {"coloredstrings:string_orange","coloredstrings:string_orange",},
    }
})
minetest.register_craft({
    output="wool:brown",
    recipe={
        {"coloredstrings:string_brown","coloredstrings:string_brown",},
        {"coloredstrings:string_brown","coloredstrings:string_brown",},
    }
})
minetest.register_craft({
    output="wool:red",
    recipe={
        {"coloredstrings:string_red","coloredstrings:string_red",},
        {"coloredstrings:string_red","coloredstrings:string_red",},
    }
})
minetest.register_craft({
    output="wool:pink",
    recipe={
        {"coloredstrings:string_pink","coloredstrings:string_pink",},
        {"coloredstrings:string_pink","coloredstrings:string_pink",},
    }
})
minetest.register_craft({
    output="wool:magenta",
    recipe={
        {"coloredstrings:string_magenta","coloredstrings:string_magenta",},
        {"coloredstrings:string_magenta","coloredstrings:string_magenta",},
    }
})
minetest.register_craft({
    output="wool:violet",
    recipe={
        {"coloredstrings:string_violet","coloredstrings:string_violet",},
        {"coloredstrings:string_violet","coloredstrings:string_violet",},
    }
})
